bosonprotocol/interface

src/components/modal/components/CreateProfile/CreateProfileModal.tsx
src/components/modal/components/CreateProfile/Lens/LensForm.tsx
src/components/modal/components/CreateProfile/Lens/LensFormFields.tsx
src/components/modal/components/CreateProfile/Lens/LensProfile.tsx
src/components/modal/components/CreateProfile/Lens/utils.ts
src/components/product/ProductType.tsx
src/pages/create-product/CreateProduct.tsx
src/pages/create-product/CreateProductInner.tsx
src/pages/profile/seller/Seller.tsx

Reverts bosonprotocol/interface#541

Revert "feat: allow to edit and override the seller lens profile when creatin…"

---

.github/workflows/ci.yaml

This adds in a couple more sellers to the curation list

chore: add seller 172, 183 curation list

---

src/components/datepicker/Calendar.tsx
src/components/datepicker/DatePicker.tsx

- Change format in input
- if you have selected the first date, the previous days are not disabled and therefore can be selected in which case if you select a second date prior the first one, this second date will be the first one and the first will be the second
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204004397340310

feat: improve ux calendar

---

src/components/form/Select.tsx
src/components/form/TagsInput.tsx
src/components/form/types.ts
src/components/modal/components/CreateProfile/Lens/LensFormFields.tsx
src/components/product/ConfirmProductDetails.tsx
src/components/product/Preview.tsx
src/components/product/ProductType.tsx
src/components/product/TermsOfExchange.tsx
src/components/product/utils/const.ts
src/components/product/utils/productHelpOptions.tsx
src/components/product/utils/termsOfExchange.ts
src/components/product/utils/validationSchema.ts
src/lib/utils/calcPrice.ts
src/lib/utils/getOfferLabel.ts
src/pages/create-product/CreateProductInner.tsx

- add coming soon 
- change "tag" to "tags"
- align tags to input
- allow setting buyer cancel pen/seller deposit with a fixed value
- add sentence to explain why chat initialization matters
- rephrase lens minimum upload text
- change font size select
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204004392877787

chore: minor improvements

---

src/components/product/ProductVariants.tsx

the flow that fixes this is the following:
- create 2 color tags
- create 1 size tag
- remove size tag
- you should see 2 variants, one for each color tag whereas before you would see none
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204064846868377

fix: variants deletion

---

src/components/header/Header.tsx

style: banner custom storefront

---

src/components/detail/DetailWidget/DetailWidget.tsx
src/components/exchange/Exchange.tsx
src/pages/chat/components/ExchangeSidePreview.tsx
src/pages/dispute-centre/DisputeList.tsx

- change copy Raise a problem in exchange widget 
- change copy Raise a problem in modals

chore: rename raise a problem to raise a dispute

---

src/components/product/utils/validationSchema.ts

fix: max commits should be greater than 0

---

package-lock.json
package.json
src/components/detail/DetailWidget/DetailWidget.tsx
src/components/exchange/Exchange.tsx

fix: force widget account to be identical to the dApp

---

src/components/detail/DetailWidget/DetailWidget.tsx
src/lib/config.ts
src/lib/utils/hooks/useOnCloseWidget.ts
src/pages/about/AboutPage.tsx
src/pages/offers/OfferDetail.tsx
src/pages/products/ProductDetail.tsx

feat: handle on close widget

---

package-lock.json
package.json
src/components/detail/DetailWidget/DetailWidget.tsx
src/components/exchange/Exchange.tsx

needed following https://github.com/bosonprotocol/widgets/issues/80 https://github.com/bosonprotocol/widgets/pull/82

chore: adapt to last changes in redemption widget

---

.env.example
.github/workflows/ci.yaml
.github/workflows/ci_reusable.yaml
src/lib/utils/hooks/useExchanges.ts

fix: image not available on exchange

---

src/lib/utils/hooks/product/useProducts.ts

fixes: https://github.com/bosonprotocol/interface/issues/923

fix: explore page error when sorting by price

---

src/components/modal/components/Profile/CreateProfileModal.tsx
src/components/modal/components/Profile/EditProfileModal.tsx
src/lib/utils/hooks/lens/fetchLens.ts
src/lib/utils/hooks/lens/profile/useGetLensProfiles.ts
src/pages/profile/seller/Seller.tsx

fix: ensure a failure to fetch the LENS profile does not crash the dApp

---

src/lib/utils/hooks/lens/profile/useGetLensProfiles.ts

fixes: https://github.com/bosonprotocol/interface/issues/953

fix: empty request to lens

---

package-lock.json
package.json
src/components/detail/DetailWidget/DetailWidget.tsx
src/components/exchange/Exchange.tsx

depends on https://github.com/bosonprotocol/core-components/pull/627 and https://github.com/bosonprotocol/widgets/pull/101

feat: redeemption widget without connecting wallet

---

src/components/form/Switch.tsx
src/components/modal/components/ExchangePolicyDetails.tsx
src/components/modal/components/Profile/CreateProfileModal.tsx
src/components/modal/components/Profile/EditProfileModal.tsx

feat: change escalation period copy and add disabled state to switch component

---

package-lock.json
package.json
src/components/detail/DetailWidget/DetailWidget.tsx
src/components/exchange/Exchange.tsx
src/components/seller/finances/SellerFinances.tsx

depends on: https://github.com/bosonprotocol/widgets/pull/105

feat: remove parent origin

---

src/components/core-sdk/CoreSDKContext.tsx
src/lib/utils/hooks/connection/connection.ts

fix: initialize coreSDK provider/signer with magic link

---

.gitignore
package-lock.json
package.json

run ```npm run ts-coverage``` and a new folder called coverage-ts will be created with a report in html

chore: add ts-coverage script

---

package-lock.json
package.json
src/components/detail/DetailWidget/BasicCommitDetailWidget.tsx
src/components/detail/DetailWidget/CommitDetailWidget.tsx
src/components/detail/DetailWidget/ExchangeDetailWidget.tsx
src/pages/common/OfferFullDescription.tsx

fix: ensure seller curation list is used in offer description

---

package-lock.json
package.json
src/components/config/ConfigProvider.tsx
src/components/offers/OfferList.tsx
src/lib/config.ts
src/pages/profile/seller/Offers.tsx
src/pages/profile/seller/Seller.tsx
src/pages/profile/seller/Tabs.tsx

fix: seller logo/cover image and name are missing from the Seller page

---

src/components/product/Preview.tsx
src/pages/create-product/CreateProductInner.tsx

fix: adapt to productV1 metadata changes

---

package-lock.json
package.json
src/components/detail/DetailWidget/ExchangeDetailWidget.tsx
src/components/ui/SellerID.tsx

fix: redeem button has no effect on the exchange details page

---

.eslintrc
package-lock.json
package.json
src/components/core-sdk/CoreSDKProvider.tsx
src/lib/utils/hooks/lens/profile/useGetLensProfiles.ts
src/lib/utils/hooks/product/useProducts.ts

- fix: some missing seller name and image in the explore page
- chore: add tanstack eslint plugin
- other minor improvements

fix: some missing seller name and image in the explore page

---

package-lock.json
package.json
src/components/product/Preview.tsx
src/pages/common/OfferFullDescription.tsx
src/pages/exchange/Exchange.tsx
src/pages/offers/OfferDetail.tsx
src/pages/products/ProductDetail.tsx
src/pages/profile/common/ReadMore.tsx

fixes: https://github.com/bosonprotocol/interface/issues/1017
updates react-kit

fix: testing issues

---

src/components/seller/exchanges/SellerExchangeTimePeriod.tsx

fix: time period column in exchanges page for offers with no expiration date

---

package-lock.json
package.json

fixes: https://github.com/bosonprotocol/interface/issues/1035

chore: upgrade react-kit

---

src/components/offers/OfferList.tsx
src/components/product/utils/const.ts
src/components/productCard/ProductCard.tsx
src/lib/config.ts
src/lib/utils/hooks/product/useProducts.ts
src/pages/landing/FeaturedOffers.tsx

fix: name and image seller product cards

---

package-lock.json
package.json
src/components/modal/components/DetailWidget.tsx
src/components/modal/components/ProductCreateSuccess.tsx
src/components/product/Preview.tsx
src/components/ui/Video.tsx
src/pages/common/OfferFullDescription.tsx
src/pages/exchange/Exchange.tsx
src/pages/offers/OfferDetail.tsx
src/pages/products/ProductDetail.tsx

depends on: https://github.com/bosonprotocol/core-components/pull/691

feat: add mute button to videos

---

src/components/modal/components/Chat/MakeProposal/steps/MakeAProposalStep/MakeAProposalStep.tsx
src/components/modal/components/Chat/MakeProposal/steps/MakeAProposalStep/RefundRequest.tsx

fixes: https://github.com/bosonprotocol/interface/issues/1043

feat: change copy shown when making a proposal if you are the seller

---

package-lock.json
package.json
src/components/detail/DetailWidget/BasicCommitDetailWidget.tsx
src/components/detail/DetailWidget/CommitDetailWidget.tsx
src/components/detail/DetailWidget/ExchangeDetailWidget.tsx
src/components/detail/const.ts
src/components/modal/components/WhatIsRedeem.tsx

fixes: https://github.com/bosonprotocol/interface/issues/1049

chore: change copies commit to commit to buy

---

package-lock.json
package.json
src/components/modal/components/Profile/Lens/LensBosonAccountForm.tsx
src/components/modal/components/Profile/bosonAccount/BosonAccountForm.tsx

following CC change https://github.com/bosonprotocol/core-components/pull/697

chore: upgrade to latest CC version

---

package-lock.json
package.json

fix https://github.com/bosonprotocol/core-components/issues/703

fix: render Contractual Agreement fails on Sepolia network

---

package-lock.json
package.json
src/components/modal/components/SellerFinance/FinanceWithdraw.tsx
src/lib/utils/number.ts

fix https://github.com/bosonprotocol/core-components/issues/706

fix: rounded values may be wrong (funds deposit/withdraw)

---

src/components/header/AnnouncementBanner.tsx
src/components/header/Header.tsx

fixes: https://github.com/bosonprotocol/interface/issues/1058

feat: add announcement banner

---

src/components/detail/DetailWidget/CommitDetailWidget.tsx
src/components/modal/components/DetailWidget.tsx
src/pages/create-product/CreateProductInner.tsx

fix: offer image in commit success modal

---

.gitignore
package-lock.json
package.json
scripts/link-to-local-chat-sdk.js
src/components/modal/components/Chat/ResolveDisputeModal.tsx
src/components/modal/components/Chat/components/EscalateModal/steps/EscalateStepTwo.tsx
src/components/modal/components/RetractDisputeModal.tsx
src/components/product/confirmProductDetailsPage/ConfirmProductDetails.tsx
src/lib/utils/hooks/chat/common.ts
src/lib/utils/hooks/chat/getThreadWorker.ts
src/lib/utils/hooks/chat/useChatStatus.ts
src/pages/chat/ChatProvider/ChatContext.ts
src/pages/chat/ChatProvider/ChatProvider.tsx
src/pages/chat/ChatProvider/const.ts
src/pages/chat/components/Message.tsx
src/pages/chat/components/MessageSeparator.tsx
src/pages/chat/components/conversation/ChatConversation.tsx
src/pages/chat/components/conversation/ChatConversationBottom.tsx
src/pages/chat/components/conversation/ChatInput.tsx
src/pages/chat/components/conversation/Messages.tsx
src/pages/chat/utils/send.ts
src/pages/dispute-centre/RaiseDisputePage.tsx

depends on https://github.com/bosonprotocol/chat-sdk/pull/63
if the above PR is not merged then pull that branch, run `npm run build` and in the interface (here) run: `npm run link-chat ../chat-sdk && rm -rf node_modules/.cache` and then `npm run dev` as always to test this

feat: upgrade xmtp
